### ISSUE TITLE
change add todo styling using tailwind only

### ISSUE THREAD

**Issue by siwamsingh** [siwamsingh/todo-react-router-redux#1]
change the add todo styling using todo .
dont make any branches of the project .
if possible try to make it look like home / main page .
currently looks like this .
<img width="514" alt="Screenshot 2023-12-24 142320" src="https://github.com/siwamsingh/todo-react-router-redux/assets/140843501/3fe44ec8-f6df-4dde-94e0-6dbe96fc5d34">

**Comment by MyBaBB** [comment]
Hi I would like this challenge.  I need something to do.
Can you describe more details how you would like it and I will create this for you

**Comment by MyBaBB** [comment]
I have never done i first issue, this would be my first first issue.

**Comment by siwamsingh** [comment]
@MyBaBB thanks fo chossing my repo you can proceed by making the add todo page something like this 
![Screenshot from 2024-01-19 13-35-52](https://github.com/siwamsingh/todo-react-router-redux/assets/140843501/d62c2e69-79bd-4feb-b218-101d418d6f4f)

no need to add the serach bar just make sure it looks some thing like this for the ADD button and X button i am leaving the design to you .

steps to procedd 

fork the repository 
make sure you have latest node and npm version
write "npm i"
use  "npm run dev" to run on local server  

feel free to ask any mare questions

**Comment by MyBaBB** [comment]
Totally awesome.  I am completely  capable of this. Although I am just learning issues on git hub. I am studying at this very moment on the subject.  This will be my next project. Thank you. You can checkout my website if you want so you know. I am at mybabb.com.

Sent from my MetroPCS 5G Android device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MyBaBB** [comment]
new guy was really into it too much.
 OK, disregard last push , I a was getting excited and was going to fix too
many things, I was going to fix the Edit list also.

I will stick to the little task first, maybe you have someone assigned to
that already ,
plus I had it on another branch and I see that you request "not another
Branch".
 I will slow down. I was about to go to town and fix everything on your
website.

**Comment by MyBaBB** [comment]
I finished,  tell me what your think,  I can alter anything,   That was a
Very satisfying experience to finally do something on my "first" - first
issue.   I think I turned it in correctly.
Let me know if I did anything not correct.   The next time I will be way
smoother in the process and I won't bug so much.   There is so much more I
can do and I tried not to get carried away.
Thanks again!!!

**Comment by MyBaBB** [comment]
if you want me to do the other edit page as well just let me know,  I
didn't know,  I mean I know that you need  that page done also but I didn'
t know if you were saving it for another first issue.

**Comment by siwamsingh** [comment]
well this was a practice project i made while learning react if you want you can contribute to this project as you wish . 
I visited your website , it was awesome i reactly liked the style . I am also new to github and opensouce and currently learning . It would be nice if we could connect on Linkedin or discord😊 
I will try adding some projects i girlscript summer of code so feel free to  follow me.

**Comment by MyBaBB** [comment]
LMAO!!  I thought you were a CEO for FlowBite or something.  I thought you
were putting out first issues as a Talent Scout or something.
I just woke from a nightmare because I didn't finish the project and I blew
it.  That is super funny.
I haven't started doing discord yet.
I have had my head in learning from scratch for about 14 months now.   I am
an older dude and I got excited last year when I learned ctrl + z.
I have studied all night and day for over this long and have
dedicated everything to it.
I forgot how to socialize and everything.
But I am here now, rubbing elbows with the big dogs.
I had to do it all on my own.  I tried reaching out in GitHub when I first
started but I had zero responders and I would not have understood them
anyways.
I just started trying Git-Hub first issues.
Yes,  I would appreciate your friendship on linked in.
I am comfortable with everything that I have learned up to this point, But
when do you know enough?  There is always more.
So, I am about 2 months into React.   I am comfortable with everything that
I have learned so far so Learning is easier.
I have a while to go Learning JavaScript  but I have the basics down.
Copilot, stack overflow can usually help me when I need it.
I am at the point now that I am trying to earn cash some way.
That is what drove me to finding issues.
I took some Certified classes in HTML and CSS when I first started but I
Studied under Dave Gray tuts on you tube and test out with 100%.
I learned way more from Dave Gray's Tuts, Among the other You tubers.

 👍   Yes,  I would appreciate your friendship on linked in.
this is an older email though and I use another, I will let you know what
my other Email when I go back into github and correct it.

**Comment by MyBaBB** [comment]
if you see another email ***@***.*** then that is supposed to be my git
hub handle. i changed it just now in settings

**Comment by MyBaBB** [comment]
I put in some work for you and created an issue.  So whenever you want it
You can look it up.   I am done for the day.   Thank you,  and I like your
linked in profile.
If you ever need anything styled up let me know.
